### PR TITLE
Allow manipulating the fake response

### PR DESCRIPTION
**Pull request by elnurvl**
You can now configure the `GlobalAuthenticationGatewayFake` class to return responses other than a `PASS` response.

### CODE REVIEW

**Comment by elnurvl** [comment]
@madmatt , this includes some bug fixes and improvements on testability. Please take a look at the PR and merge it as soon as possible. Ideally, it would be nice if you could do it today. Thanks.

**Comment by madmatt** [comment]
Hey @elnurvl, this is fantastic - thank you! I actually have been working on adding a linting pass and have done almost exactly the same thing as you in that branch 😂 

Yours looks great though, so I'll merge yours and then rebase my changes on top of yours.

**Comment by elnurvl** [comment]
Thank you, @madmatt . Can you please tag the commit and release the new version?

Linting check will be a great help! It can be easy to violate the styling guidelines during the development.

**Comment by madmatt** [comment]
Hey @elnurvl, [version 1.0.2](https://github.com/madmatt/id3global-service/releases/tag/1.0.2) is out now :)

**Pull request merged**
