### PR TITLE
Remove unnecessary composer.lock file

### PR DESCRIPTION
**Pull request by madmatt**
This is only required for actual projects, not for a Composer module.

### CODE REVIEW

**Comment by madmatt** [comment]
@Firesphere Mind having a quick check of this? Ta!

**Comment by Firesphere** [comment]
I'll give it a run next week :) But should be okay IMO :)

**Comment by Firesphere** [comment]
I spoke too early.

```
Package madmatt/id3global-service at version  has a PHP requirement incompatible with your PHP version (7.1.20)
```

**Comment by madmatt** [comment]
That's okay - that was fixed in pull request #8, which was merged after this PR was opened - so once it's merged it'll be fine :)

**Pull request merged**
